# Generated by Django 4.2.24 on 2025-10-27 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0004_alter_chatmessage_options_alter_conversation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="agent_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("document_agent", "Document Agent"),
                    ("corpus_agent", "Corpus Agent"),
                ],
                help_text="The specific agent type that generated this message (for LLM messages)",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the message was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent message for threaded replies",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="conversations.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="conversation_type",
            field=models.CharField(
                choices=[("chat", "Chat"), ("thread", "Thread")],
                default="chat",
                help_text="Type of conversation: chat (agent-based) or thread (discussion)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the conversation was soft-deleted",
                null=True,
            ),
        ),
    ]
