# Generated by Django 4.2.24 on 2025-11-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0007_corpusmoderator_conversation_is_locked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text="Parent message for threaded replies",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="conversations.chatmessage",
            ),
        ),
    ]
