# Generated by Django 4.2.24 on 2025-11-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0008_alter_chatmessage_parent_message"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["deleted_at"], name="conversatio_deleted_978225_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["deleted_at"], name="conversatio_deleted_4f00fa_idx"
            ),
        ),
    ]
