# Generated by Django 4.2.24 on 2025-11-07 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("conversations", "0009_add_deleted_at_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="agent_configuration",
            field=models.ForeignKey(
                blank=True,
                help_text="Which agent generated this message (if msgType != HUMAN)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="agents.agentconfiguration",
            ),
        ),
    ]
