# Generated by Django 4.2.24 on 2025-11-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_ensure_default_agents"),
        ("conversations", "0010_chatmessage_agent_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="mentioned_agents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Agents mentioned in this message that should respond",
                related_name="mentioned_in_messages",
                to="agents.agentconfiguration",
            ),
        ),
    ]
