# Generated by Django 4.2.24 on 2025-11-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0007_corpusmoderator_conversation_is_locked_and_more"),
        ("annotations", "0046_add_relationship_privacy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="References the Conversation that this embedding belongs to (if any).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedding_set",
                to="conversations.conversation",
            ),
        ),
        migrations.AddField(
            model_name="embedding",
            name="message",
            field=models.ForeignKey(
                blank=True,
                help_text="References the ChatMessage that this embedding belongs to (if any).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedding_set",
                to="conversations.chatmessage",
            ),
        ),
    ]
