# Generated by Django 4.2.24 on 2025-11-23 15:54

from django.db import migrations, models
import functools
import opencontractserver.shared.utils


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0048_add_structural_annotation_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuralannotationset",
            name="pawls_parse_file",
            field=models.FileField(
                blank=True,
                help_text="PAWLS JSON parse data for this content",
                max_length=1024,
                null=True,
                upload_to=functools.partial(
                    opencontractserver.shared.utils.calc_oc_file_path,
                    *(),
                    **{"sub_folder": "pawls_layers_files"}
                ),
            ),
        ),
        migrations.AlterField(
            model_name="structuralannotationset",
            name="txt_extract_file",
            field=models.FileField(
                blank=True,
                help_text="Plain text extraction for this content",
                max_length=1024,
                null=True,
                upload_to=functools.partial(
                    opencontractserver.shared.utils.calc_oc_file_path,
                    *(),
                    **{"sub_folder": "txt_layers_files"}
                ),
            ),
        ),
    ]
