# Generated by Django 4.2.24 on 2025-10-27 01:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_user_cookie_consent_accepted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this installation",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Installation Date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Installation",
                "verbose_name_plural": "Installation",
            },
        ),
    ]
