# Generated by Django 4.2.24 on 2025-11-05 19:38

from django.db import migrations, models
import opencontractserver.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_installation"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", opencontractserver.users.models.UserProfileManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_profile_public",
            field=models.BooleanField(
                default=True,
                help_text="Whether this user's profile is visible to other users",
                verbose_name="Public Profile",
            ),
        ),
    ]
