# Generated by Django 4.2.24 on 2025-11-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0003_alter_badge_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={
                "ordering": ["-created"],
                "permissions": (
                    ("permission_badge", "permission badge"),
                    ("publish_badge", "publish badge"),
                    ("create_badge", "create badge"),
                    ("read_badge", "read badge"),
                    ("update_badge", "update badge"),
                    ("remove_badge", "remove badge"),
                ),
            },
        ),
    ]
