# Generated by Django 4.2.23 on 2025-10-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0021_alter_corpusaction_options_alter_corpusquery_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpus",
            name="corpus_agent_instructions",
            field=models.TextField(
                blank=True,
                help_text="Custom system instructions for the corpus-level agent. If not set, uses DEFAULT_CORPUS_AGENT_INSTRUCTIONS from settings.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="corpus",
            name="document_agent_instructions",
            field=models.TextField(
                blank=True,
                help_text="Custom system instructions for document-level agents in this corpus. If not set, uses DEFAULT_DOCUMENT_AGENT_INSTRUCTIONS from settings.",
                null=True,
            ),
        ),
    ]
