# Generated by Django 4.2.24 on 2025-11-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0024_corpusfolder_corpusdocumentfolder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpusfolder",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
