# Generated by Django 4.2.16
"""
Drop the CorpusDocumentFolder model.

This model was created as part of the dual-system architecture for folder assignments,
but it was never deployed to production. DocumentPath.folder is the single source of
truth for document folder assignments in the corpus.

This migration removes the CorpusDocumentFolder table entirely.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corpuses", "0025_corpusfolder_is_public"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CorpusDocumentFolder",
        ),
    ]
