# Generated by Django 4.2.24 on 2025-11-17 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0024_initialize_dual_tree_versioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Original document this was copied from (cross-corpus provenance). Implements Rule I2.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corpus_copies",
                to="documents.document",
            ),
        ),
    ]
