# Generated by Django 4.2.24 on 2025-11-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0048_add_structural_annotation_set"),
        ("documents", "0025_add_source_document_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="structural_annotation_set",
            field=models.ForeignKey(
                blank=True,
                help_text="Shared structural annotations for this document's content",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="annotations.structuralannotationset",
            ),
        ),
    ]
